[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
peerpiper = { path = "crates/peerpiper" }
peerpiper-core = { path = "crates/peerpiper-core" }
peerpiper-native = { path = "crates/peerpiper-native" }
peerpiper-browser = { path = "crates/peerpiper-browser" }
futures = "0.3.29"
rand = "0.8"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git" }
bitflags = "2.5.0"
wit-bindgen-rt = "0.22.0"

[profile.release]
opt-level = "z"          # Optimize for size.
lto = true              # Link Time Optimization
codegen-units = 1        # allow for maximum size reduction optimizations
strip = true             # Automatically strip symbols from the binary.
panic = 'abort'          # Abort on panic
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
rpath = false

[patch.crates-io]
# patch with https://github.com/bytecodealliance/wit-bindgen/commit/9c913f6d119739a09b521deed89743b4a001aae1
wit-bindgen-rt = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "9c913f6" }
