[workspace]
members = [
  "crates/*"
]
resolver = "2"

[workspace.dependencies]
peerpiper = { path = "crates/peerpiper" }
peerpiper-core = { path = "crates/peerpiper-core" }
peerpiper-native = { path = "crates/peerpiper-native" }
peerpiper-browser = { path = "crates/peerpiper-browser" }
futures = "0.3.29"
rand = "0.8"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git" }
