set dotenv-load

# use cargo to start the server with the cloudflare feature
serve:
  cargo run --features cloudflare

# Secure Copy Protocol (SCP) command to copy files to a remote server
scp:
  scp -i ~/.ssh/oracle_cloud ../../target/release/peerpiper-server ubuntu@$IP_ADDRESS:~

connect:
  ssh -i ~/.ssh/oracle_cloud ubuntu@$IP_ADDRESS
