[package]
name = "peerpiper-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
futures = "0.3.29"
rand = "0.8"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
cfg-if = "1"
thiserror = "1.0.50"

js-sys = "0.3.66"

peerpiper-core = { workspace = true }

libp2p = { workspace = true, features = [ "ed25519", "macros", "ping", "wasm-bindgen"] }
libp2p-webrtc-websys = { git = "https://github.com/libp2p/rust-libp2p.git" }
tracing-wasm = "0.2.1"

wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.38"

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["js"] }
