name: Rust Build and Test

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # This will fetch all submodules recursively

      - name: install Rust  
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: 1.83.0
            targets: wasm32-unknown-unknown, wasm32-wasip1
              
      - name: Verify Rust targets
        run: rustup target list --installed

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: wasm-pack@0.12.0

      - name: Install Just
        uses: extractions/setup-just@v2

      # binstall is faster than cargo install
      - name: Install binstall
        uses: taiki-e/install-action@cargo-binstall
        
      # We'll need cargo-component to build WIT Components in the Just commands
      - name: Install cargo-component
        run: echo yes | cargo binstall cargo-component     

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Ensure targets are installed
        run: rustup target add wasm32-unknown-unknown wasm32-wasip1

      - name: Verify targets
        run: rustup target list --installed

      - name: Run tests
        run: just test

