name: Rust Build and Test

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  # pre-build:
  #   name: Pre-Build wasm binaries
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: recursive  # This will fetch all submodules recursively
  #
  #     - uses: extractions/setup-just@v2
  #
  #     # binstall is faster than cargo install
  #     - name: Install binstall
  #       uses: taiki-e/install-action@cargo-binstall
  #
  #     - name: Install cargo-component
  #       run: echo yes | cargo binstall cargo-component
  #
  #     - name: install Rust  
  #       uses: dtolnay/rust-toolchain@stable
  #       with:
  #         targets: wasm32-unknown-unknown
  #
  #     - run: just update-build
  #
  #     - name: upload artifacts to target
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: wasm-files-target 
  #         path: target/wasm32-wasip1/**/*.wasm
  #         overwrite: true

  test:
    name: Build and Test
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # This will fetch all submodules recursively

      - name: install Rust  
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      
      - name: Install Just
        uses: extractions/setup-just@v2

      # binstall is faster than cargo install
      - name: Install binstall
        uses: taiki-e/install-action@cargo-binstall
        
      # We'll need cargo-component to build WIT Components in the Just commands
      - name: Install cargo-component
        run: echo yes | cargo binstall cargo-component     

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Run tests
        run: just test

